services:
  - type: web
    name: paywatch
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: APP_URL
        value: https://www.criptomining.store
